import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href={"/"}>홈</Link>
          <Link href={"/list"}>List</Link>
          <Link href={"/cart"}>Cart</Link>
        </div>
        {children}
      </body>
    </html>
  );
}

// layout.js는 전역 CSS를 가져오고, 메타데이터를 정의하고, 루트 레이아웃을 정의합니다.
// 리액트에서 헤더, 푸터, 레이아웃을 정의하는 것과 같습니다.
